#!/bin/bash
echo "Deploy this application into remote server"
ssh -i /home/ubuntu/jenkins ubuntu@13.233.160.245 <<EOF
sudo su
cd /home/ubuntu/angular-realworld-example-app/
git pull
ng build --prod
cd dist
sudo rm -rf /var/www/html/*
sudo mv * /var/www/html
sudo systemctl restart nginx
sudo systemctl status nginx
EOF
#!/bin/bash
